# Generated by Django 4.0.3 on 2022-04-04 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profesionales', '0003_alter_cerrajero_folleto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cerrajero',
            name='folleto',
        ),
    ]
